---
# tasks file for roles/gitlab_setup

---
- name: Setup Gitlab Service
  import_tasks: gitlab-setup.yml
  tags:
    - install_gitlab
    - setup_gitlab

- name: Setup backup for gitlab service
  import_tasks: gitlab-backup.yml
  tags:
    - backup_gitlab
    - setup_gitlab